packages:
  - "apps/test/*"
  
  - "packages/*"
  - "apps/*"

catalog:
  # TYPES
  typescript: 5.7.3
  "@types/node": ^20.10.5
  "@types/mocha": ^10.0.8

  # ESLINT + PRETTIER
  eslint: ^9.0.0
  prettier: ^3.0.0
  # ⇑ PLUGINS
  eslint-config-prettier: ^9
  eslint-plugin-prettier: ^5

  # ENVIRONMENT
  dotenv: ^16.4.7
  fock-logger: 2.3.1

  # DEV
  nodemon: ^3.1.9
  ts-node: ^10.9.2
  tsc-alias: ^1.8.10
  tsconfig-paths: ^4.2.0
  mocha: 11.5.0
  ts-mocha: 11.1.0
  expect: 30.0.0-beta.3

  # HTTP
  axios: ^1.7.9

  # DATABASE
  mongodb: ^6.8.0
  mongoose: ^8.9.5
