packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@types/node": "^20.10.5"
  "dotenv": "^16.4.7"
  "nodemon": "^3.1.9"
  "ts-node": "^10.9.2"
  "tsc-alias": "^1.8.10"
  "tsconfig-paths": "^4.2.0"
  "typescript": "^5.3.3"

  "axios": "^1.7.9"

  "fock-logger": "2.3.1"

  "mongodb": "^6.8.0"
  "mongoose": "^8.5.3"