# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

permissions:
  contents: write

jobs:
  scan_and_fix:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 10.4.0

      - uses: actions/setup-node@v4
        name: Node.js ⇒ ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: pnpm ⇒ Install dependencies
        run: pnpm install

      - name: \[BACKEND] Eslint ⇒ Scan and fix
        run: pnpm --filter backend run lint
        continue-on-error: true

      - name: \[FRONTEND] Code Style ⇒ Scan and fix
        run: |
          pnpm --filter frontend run format
          pnpm --filter frontend run lint
        continue-on-error: true

      - name: Save Changes ⇒ Commit formatted code
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m '${{ github.event.head_commit.message }} (formatted)'
          git push
        continue-on-error: true
