name: Code Scanner

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  eslint:
    name: Scanner
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ESLint
        run: |
          npm install eslint@8.10.0

      - name: Run ESLint
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: npx eslint .
          --config .eslintrc.js
          --ext .js,.jsx,.ts,.tsx
        continue-on-error: true

  prettier:
    name: Prettier
    runs-on: ubunti-latest

    permissions:
      contents: write
      security-events: write
      actions: read

    steps:
      - name: Install Prettier
        run: |
          npm install prettier@latest

      - name: Run Prettier
        run: npx prettier .
          --config .prettierrc
          --write
        continue-on-error: true